### PR TITLE
[YouTube] Add support for video lockup content type

### LINKED ISSUE #1314: [YT] A/B Test: Related Items contentType -> LOCKUP_CONTENT_TYPE_VIDEO
### Checklist

- [x] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipeExtractor/releases/latest).
- [x] I am aware that this issue is being opened for the NewPipe Extractor, NOT the [app](https://github.com/TeamNewPipe/NewPipe), and my bug report will be dismissed otherwise.
- [x] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipeExtractor/issues) or [closed](https://github.com/TeamNewPipe/NewPipeExtractor/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [x] This issue contains only one bug.
- [x] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.6

### Steps to reproduce the bug

Sometimes no related videos/items are displayed/extracted.

The problem has been around for a longer time as I already noticed this back in February when some test sporadically failed.

This is because YT changed the API and sometimes returns ``LOCKUP_CONTENT_TYPE_VIDEO``.

Details can be seen here:
Image

Example JSON:

[lockupViewModel.json](https://github.com/user-attachments/files/21091369/lockupViewModel.json)

### PR DESCRIPTION
**Pull request by litetex**
Fixes #1314
Fixes TeamNewPipe/NewPipe#12422 

Todo:
- [x] Address TODO comments
- [x] Requires https://github.com/TeamNewPipe/nanojson/pull/26 please merge this first

---

Todo for @litetex :

- [x] Create an issue to convert ``ParsingException`` to ``RuntimeException`` because otherwise the Java Streaming API sucks (because you can't use it) https://github.com/TeamNewPipe/NewPipeExtractor/issues/1328
- [x] Create an issue to check in code format/styling for IntelliJ (and maybe remove the checkstyle check that always runs when building and only run it in the CI) https://github.com/TeamNewPipe/NewPipeExtractor/issues/1329

---

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [ ] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

### CODE REVIEW

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java [hunk 1]
```diff
@@ -0,0 +1,278 @@
+/*
+ * Copyright (C) 2016 Christian Schabesberger <chris.schabesberger@mailbox.org>
+ * YoutubeStreamInfoItemExtractor.java is part of NewPipe Extractor.
```
Comment (AudricV) [inline extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java]: This needs to be modified.

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java [hunk 2]
```diff
@@ -0,0 +1,278 @@
...
+                .getObject("imageType")
+                .getObject("image")
+                .getArray("sources")
+                .streamAsJsonObjects())
+            .map(jsonObject -> jsonObject
+                .getObject("clientResource")
+                .getString("imageName"))
+            .map("CHECK_CIRCLE_FILLED"::equals)
+            .findFirst()
+            .orElse(false);
```
Comment (AudricV) [inline extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java]: Use `YoutubeParsingHelper.hasArtistOrVerifiedIconBadgeAttachment` instead.

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java [hunk 3]
```diff
@@ -0,0 +1,278 @@
...
+            final String videoId = lockupViewModel.getString("contentId");
+            return YoutubeStreamLinkHandlerFactory.getInstance().getUrl(videoId);
+        } catch (final Exception e) {
+            throw new ParsingException("Could not get url", e);
+        }
+    }
+
+    @Override
+    public String getName() throws ParsingException {
+        // TODO Is there Formatting?
```
Comment (AudricV) [inline extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java]: No, there should be no formatting.

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java [hunk 4]
```diff
@@ -0,0 +1,278 @@
...
+        final String name = getName(); // only get it once
+        return "[Private video]".equals(name)
+            || "[Deleted video]".equals(name);
+    }
+
+    @Override
+    public String getUrl() throws ParsingException {
+        try {
+            final String videoId = lockupViewModel.getString("contentId");
+            return YoutubeStreamLinkHandlerFactory.getInstance().getUrl(videoId);
```
Comment (AudricV) [inline extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java]: You should add a fallback to `rendererContext.commandContext.onTap.innertubeCommand.watchEndpoint.videoId`.

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java [hunk 5]
```diff
@@ -0,0 +1,278 @@
...
+
+    @Nullable
+    @Override
+    public String getShortDescription() throws ParsingException {
+        return null;
+    }
+
+    @Override
+    public boolean isShortFormContent() throws ParsingException {
+        // TODO Detect with samples
```
Comment (AudricV) [inline extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java]: Shorts seem to be still returned as `compactVideoRenderer`s, I got two of them within `lockupViewModels`.

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java
Comment (AudricV) [inline extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java:1]: Some methods are protected in this class, they only need to be private.

**Review by AudricV — CHANGES_REQUESTED** [review]
Thank you. I don't think nanojson changes should go with this PR, as we want to release a new extractor and app version pretty fast. We also want to get rid of this library at some point for something else more efficient.

Please address the following changes and add support for lives (some assumptions you made are wrong for this stream type). Here is a live `lockupViewModel`, with unneeded fields truncated:

<details>

```json
{
  "contentImage": {
    "thumbnailViewModel": {
      "image": {
        "sources": [
          {
            "url": "https://i.ytimg.com/vi/v5oJO79hHLE/hqdefault.jpg?v=686c38a1&sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCbLDWlnA3yHr3nIXcorQ2ocC1V6w",
            "width": 168,
            "height": 94
          },
          {
            "url": "https://i.ytimg.com/vi/v5oJO79hHLE/hqdefault.jpg?v=686c38a1&sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCYo3hsLN7uAwIiCCs-8V6MSZorTw",
            "width": 336,
            "height": 188
          }
        ]
      },
      "overlays": [
        {
          "thumbnailOverlayBadgeViewModel": {
            "thumbnailBadges": [
              {
                "thumbnailBadgeViewModel": {
                  "icon": {
                    "sources": [
                      {
                        "clientResource": {
                          "imageName": "LIVE"
                        }
                      }
                    ]
                  },
                  "text": "EN DIRECT",
                  "badgeStyle": "THUMBNAIL_OVERLAY_BADGE_STYLE_LIVE",
                  "animationActivationTargetId": "v5oJO79hHLE",
                  "animationActivationEntityKey": "Eh8veW91dHViZS9hcHAvd2F0Y2gvcGxheWVyX3N0YXRlIMMCKAE%3D",
                  "lottieData": {
                    "url": "https://www.gstatic.com/youtube/img/lottie/audio_indicator/audio_indicator_v2.json",
                    "settings": {
                      "loop": true,
                      "autoplay": true
                    }
                  },
                  "animatedText": "En cours de lecture",
                  "animationActivationEntitySelectorType": "THUMBNAIL_BADGE_ANIMATION_ENTITY_SELECTOR_TYPE_PLAYER_STATE"
                }
              }
            ],
            "position": "THUMBNAIL_OVERLAY_BADGE_POSITION_BOTTOM_END"
          }
        }
      ]
    }
  },
  "metadata": {
    "lockupMetadataViewModel": {
      "title": {
        "content": "PBS News Hour live episode, July 7, 2025"
      },
      "image": {
        "decoratedAvatarViewModel": {
          "avatar": {
            "avatarViewModel": {
              "image": {
                "sources": [
                  {
                    "url": "https://yt3.ggpht.com/3qIMp79Z-ynhtXTYyNcdybHwvtILVk_jNMKTLbasP8F1UYCdtU-FFjTJPNGQCp5KZuNUQ62n9Gk=s68-c-k-c0x00ffffff-no-rj",
                    "width": 68,
                    "height": 68
                  }
                ]
              },
              "avatarImageSize": "AVATAR_SIZE_M"
            }
          },
          "a11yLabel": "Accéder à la chaîne",
          "rendererContext": {
            "commandContext": {
              "onTap": {
                "innertubeCommand": {
                  "commandMetadata": {
                    "webCommandMetadata": {
                      "url": "/@PBSNewsHour",
                      "webPageType": "WEB_PAGE_TYPE_CHANNEL",
                      "apiUrl": "/youtubei/v1/browse"
                    }
                  },
                  "browseEndpoint": {
                    "browseId": "UC6ZFN9Tx6xh-skXCuRHCDpQ",
                    "canonicalBaseUrl": "/@PBSNewsHour"
                  }
                }
              }
            }
          }
        }
      },
      "metadata": {
        "contentMetadataViewModel": {
          "metadataRows": [
            {
              "metadataParts": [
                {
                  "text": {
                    "content": "PBS NewsHour",
                    "attachmentRuns": [
                      {
                        "element": {
                          "type": {
                            "imageType": {
                              "image": {
                                "sources": [
                                  {
                                    "clientResource": {
                                      "imageName": "CHECK_CIRCLE_FILLED"
                                    },
                                    "width": 14,
                                    "height": 14
                                  }
                                ]
                              }
                            }
                          }
                        }
                      }
                    ]
                  }
                }
              ]
            },
            {
              "metadataParts": [
                {
                  "text": {
                    "content": "7,9 k spectateurs"
                  }
                }
              ]
            }
          ],
          "delimiter": " • "
        }
      }
    }
  },
  "contentId": "v5oJO79hHLE",
  "contentType": "LOCKUP_CONTENT_TYPE_VIDEO",
  "rendererContext": {
    "accessibilityContext": {
      "label": "PBS News Hour live episode, July 7, 2025"
    },
    "commandContext": {
      "onTap": {
        "innertubeCommand": {
          "clickTrackingParams": "",
          "commandMetadata": {
            "webCommandMetadata": {
              "url": "/watch?v=v5oJO79hHLE",
              "webPageType": "WEB_PAGE_TYPE_WATCH"
            }
          },
          "watchEndpoint": {
            "videoId": "v5oJO79hHLE"
          }
        }
      }
    }
  }
}
```
</details>

For premieres, I don't have a way to get one sadly.

If you need help, don't hesitate to ask :)

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java
Comment (litetex) [reply extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java:1]: I'm usually a fan of protected because we write a library and people might want to override stuff their way, however for now I will revert the changes

Comment (AudricV) [reply extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java:1]: Well, this is not something part of the public API clients should use.

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java (hunk 5 above)
Comment (litetex) [reply extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java]: I tried to find a video with shorts recommendations but was unable to find a single one (just compilations of shorts lol).
Could you share some example data? :)

**Comment by litetex** [comment]
> I don't think nanojson changes should go with this PR

The changes are just 2 new small additional shorthand methods which make writing the code a lot easier, so I would heavily recommend to add them.

**Comment by litetex** [comment]
There are currently problems when we encounter videos with multiple uploaders:

https://www.youtube.com/watch?v=Nxk6aRHi664
grafik

**Comment by litetex** [comment]
> There are currently problems when we encounter videos with multiple uploaders

Should be fixed now. A example mock for this will be added with #1332

File: extractor/build.gradle [hunk 6]
```diff
@@ -29,6 +29,7 @@ ext {
 dependencies {
     implementation project(':timeago-parser')
 
+    // TODO Replace with NewPipe
```
Comment (AudricV) [inline extractor/build.gradle]: Unneeded comment now :)

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java [hunk 7]
```diff
@@ -0,0 +1,371 @@
...
+import javax.annotation.Nonnull;
+import javax.annotation.Nullable;
+
+/**
+ * Note:
+ * This extractor is currently (2025-07) only used to extract related video streams.<br/>
+ * The following features are currently not implemented because they have never been observed:
+ * <ul>
+ *     <li>Shorts</li>
+ *     <li>Premiers</li>
```
Comment (AudricV) [inline extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java]:
```suggestion
 *     <li>Premieres</li>
```

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java [hunk 8]
```diff
@@ -0,0 +1,371 @@
...
+ *     <li>Premium content</li>
```
Comment (AudricV) [inline extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java]:
```suggestion
 *     <li>Paid content (Premium, members first or only)</li>
```

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java [hunk 9]
```diff
@@ -0,0 +1,371 @@
...
+                .getArray("thumbnailBadges")
+                .streamAsJsonObjects())
+            .map(jsonObject -> jsonObject
+                .getObject("thumbnailBadgeViewModel")
+                .getString("text"))
+            .collect(Collectors.toList());
+
+        if (potentialDurations.isEmpty()) {
+            throw new ParsingException("Could not get duration: No parsable durations detected");
+        }
```
Comment (AudricV) [inline extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java:158]: I think this has been not adjusted for lives.

File: timeago-generator/build.gradle [hunk 10]
```diff
@@ -1,4 +1,5 @@
 dependencies {
+    // TODO Replace with NewPipe
```
Comment (AudricV) [inline timeago-generator/build.gradle]: This leftover comment needs to be removed too :)

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java (hunk 9 above)
Comment (litetex) [reply extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java:158]: Done

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java [hunk 11]
```diff
@@ -0,0 +1,384 @@
...
+
+        return StreamType.VIDEO_STREAM;
+    }
+
+    @Override
+    public boolean isAd() throws ParsingException {
+        final String name = getName(); // only get it once
+        return "[Private video]".equals(name)
+            || "[Deleted video]".equals(name);
```
Comment (Stypox) [inline extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java]: Since we already have a layer of caching in `getName()`:

```suggestion
        return "[Private video]".equals(getName())
            || "[Deleted video]".equals(getName());
```

but anyways, this is very minor.

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java [hunk 12]
```diff
@@ -0,0 +1,384 @@
...
+                parsingException = ex;
+            }
+        }
+
+        throw new ParsingException("Could not get duration", parsingException);
+    }
+
+    @Override
+    public String getUploaderName() throws ParsingException {
+        return metadataPart(0, 0)
```
Comment (Stypox) [inline extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java:174]: Can we trust the indices to be stable? I guess we can't do much better anyway, so let's try like this for now. If it creates problems, we can always use other ways to detect the right metadata parts in the future, e.g.:
- the channel name object has "attachmentRuns" and "styleRuns" attached to it, which view count and upload date don't have
- the view count contains the "views" string or the "watching" string (for lives)
- the remaining item is the upload date

<details><summary>See here</summary>


```json
[
  {
    "metadataParts": [
      {
        "text": {
          "content": "Justin Bieber",
          "styleRuns": [
            {
              "startIndex": 13,
              "styleRunExtensions": {
                "styleRunColorMapExtension": {
                  "colorMap": [
                    {
                      "key": "USER_INTERFACE_THEME_LIGHT",
                      "value": 4284506208
                    },
                    {
                      "key": "USER_INTERFACE_THEME_DARK",
                      "value": 4289374890
                    }
                  ]
                }
              }
            }
          ],
          "attachmentRuns": [
            {
              "startIndex": 13,
              "length": 0,
              "element": {
                "type": {
                  "imageType": {
                    "image": {
                      "sources": [
                        {
                          "clientResource": {
                            "imageName": "AUDIO_BADGE"
                          },
                          "width": 14,
                          "height": 14
                        }
                      ]
                    }
                  }
                },
                "properties": {
                  "layoutProperties": {
                    "height": {
                      "value": 14,
                      "unit": "DIMENSION_UNIT_POINT"
                    },
                    "width": {
                      "value": 14,
                      "unit": "DIMENSION_UNIT_POINT"
                    },
                    "margin": {
                      "left": {
                        "value": 4,
                        "unit": "DIMENSION_UNIT_POINT"
                      }
                    }
                  }
                }
              },
              "alignment": "ALIGNMENT_VERTICAL_CENTER"
            }
          ]
        }
      }
    ]
  },
  {
    "metadataParts": [
      {
        "text": {
          "content": "157M views"
        }
      },
      {
        "text": {
          "content": "5 years ago"
        }
      }
    ]
  },
  {
    "badges": [
      {
        "badgeViewModel": {
          "badgeText": "Free with ads",
          "badgeStyle": "BADGE_COMMERCE",
          "trackingParams": "COcBENTEDBgBIhMIs6r8_ZS9jgMVOxYGAB1LCied"
        }
      },
      {
        "badgeViewModel": {
          "badgeText": "T",
          "badgeStyle": "BADGE_DEFAULT",
          "trackingParams": "COcBENTEDBgBIhMIs6r8_ZS9jgMVOxYGAB1LCied"
        }
      }
    ]
  }
]
```
</details>

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java [hunk 13]
```diff
@@ -0,0 +1,384 @@
...
+    @Override
+    public String getTextualUploadDate() throws ParsingException {
+        if (cachedTextualUploadDate != null) {
+            return cachedTextualUploadDate.orElse(null);
+        }
+
+        // This might be null e.g. for live streams
+        this.cachedTextualUploadDate = metadataPart(1, 1)
+            .map(this::getTextContentFromMetadataPart);
+        return cachedTextualUploadDate.orElse(null);
```
Comment (Stypox) [inline extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java:232]: Just in case YouTube adds more metadata items in the row 1 (which might then lead to a separate metadata item being selected at pos 1,1 instead of the upload date in case of lives), I'd first check if the stream type is a live and return null in that case

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java [hunk 14]
```diff
@@ -0,0 +1,384 @@
...
+
+    @Override
+    public long getViewCount() throws ParsingException {
+        final Optional<String> optTextContent = metadataPart(1, 0)
+            .map(this::getTextContentFromMetadataPart);
+        // We could do this inline if the ParsingException would be a RuntimeException -.-
+        if (optTextContent.isPresent()) {
+            return getViewCountFromViewCountText(optTextContent.get());
+        }
+        return -1;
```
Comment (Stypox) [inline extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java]: I think it should return `0` instead of `-1` here if the stream type is a live: livestreams with no watchers just don't have that piece of metadata (i.e. they have just one metadata row), see below:

<details><summary>JSON data</summary>


```json
{
  "lockupViewModel": {
    "contentImage": {
      "thumbnailViewModel": {
        "image": {
          "sources": [
            {
              "url": "https://i.ytimg.com/vi/vUuj6M8MgCg/hqdefault.jpg?v=67bf56f3&sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDfp6-ccdzPNoNIt4ky0na4NriaWg",
              "width": 168,
              "height": 94
            },
            {
              "url": "https://i.ytimg.com/vi/vUuj6M8MgCg/hqdefault.jpg?v=67bf56f3&sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDr0W8DMjGI9oA7P95I2tzh2hR_oQ",
              "width": 336,
              "height": 188
            }
          ]
        },
        "overlays": [
          {
            "thumbnailOverlayBadgeViewModel": {
              "thumbnailBadges": [
                {
                  "thumbnailBadgeViewModel": {
                    "icon": {
                      "sources": [
                        {
                          "clientResource": {
                            "imageName": "LIVE"
                          }
                        }
                      ]
                    },
                    "text": "LIVE",
                    "badgeStyle": "THUMBNAIL_OVERLAY_BADGE_STYLE_LIVE",
                    "animationActivationTargetId": "vUuj6M8MgCg",
                    "animationActivationEntityKey": "Eh8veW91dHViZS9hcHAvd2F0Y2gvcGxheWVyX3N0YXRlIMMCKAE%3D",
                    "lottieData": {
                      "url": "https://www.gstatic.com/youtube/img/lottie/audio_indicator/audio_indicator_v2.json",
                      "settings": {
                        "loop": true,
                        "autoplay": true
                      }
                    },
                    "animatedText": "Now playing",
                    "animationActivationEntitySelectorType": "THUMBNAIL_BADGE_ANIMATION_ENTITY_SELECTOR_TYPE_PLAYER_STATE"
                  }
                }
              ],
              "position": "THUMBNAIL_OVERLAY_BADGE_POSITION_BOTTOM_END"
            }
          },
          {
            "thumbnailHoverOverlayToggleActionsViewModel": {
              "buttons": [
                {
                  "toggleButtonViewModel": {
                    "defaultButtonViewModel": {
                      "buttonViewModel": {
                        "iconName": "WATCH_LATER",
                        "onTap": {
                          "innertubeCommand": {
                            "clickTrackingParams": "CAkQ8FsiEwjwic3PoL2OAxVM8EkHHQ_HOuw=",
                            "commandMetadata": {
                              "webCommandMetadata": {
                                "sendPost": true,
                                "apiUrl": "/youtubei/v1/browse/edit_playlist"
                              }
                            },
                            "playlistEditEndpoint": {
                              "playlistId": "WL",
                              "actions": [
                                {
                                  "addedVideoId": "vUuj6M8MgCg",
                                  "action": "ACTION_ADD_VIDEO"
                                }
                              ]
                            }
                          }
                        },
                        "accessibilityText": "Watch later",
                        "style": "BUTTON_VIEW_MODEL_STYLE_OVERLAY_DARK",
                        "trackingParams": "CAkQ8FsiEwjwic3PoL2OAxVM8EkHHQ_HOuw=",
                        "type": "BUTTON_VIEW_MODEL_TYPE_TONAL",
                        "buttonSize": "BUTTON_VIEW_MODEL_SIZE_COMPACT",
                        "state": "BUTTON_VIEW_MODEL_STATE_ACTIVE"
                      }
                    },
                    "toggledButtonViewModel": {
                      "buttonViewModel": {
                        "iconName": "CHECK",
                        "onTap": {
                          "innertubeCommand": {
                            "clickTrackingParams": "CAgQ8FsiEwjwic3PoL2OAxVM8EkHHQ_HOuw=",
                            "commandMetadata": {
                              "webCommandMetadata": {
                                "sendPost": true,
                                "apiUrl": "/youtubei/v1/browse/edit_playlist"
                              }
                            },
                            "playlistEditEndpoint": {
                              "playlistId": "WL",
                              "actions": [
                                {
                                  "action": "ACTION_REMOVE_VIDEO_BY_VIDEO_ID",
                                  "removedVideoId": "vUuj6M8MgCg"
                                }
                              ]
                            }
                          }
                        },
                        "accessibilityText": "Added",
                        "style": "BUTTON_VIEW_MODEL_STYLE_OVERLAY_DARK",
                        "trackingParams": "CAgQ8FsiEwjwic3PoL2OAxVM8EkHHQ_HOuw=",
                        "type": "BUTTON_VIEW_MODEL_TYPE_TONAL",
                        "buttonSize": "BUTTON_VIEW_MODEL_SIZE_COMPACT",
                        "state": "BUTTON_VIEW_MODEL_STATE_ACTIVE"
                      }
                    },
                    "isToggled": false,
                    "trackingParams": "CAIQ1MQMGBUiEwjwic3PoL2OAxVM8EkHHQ_HOuw="
                  }
                },
                {
                  "toggleButtonViewModel": {
                    "defaultButtonViewModel": {
                      "buttonViewModel": {
                        "iconName": "ADD_TO_QUEUE_TAIL",
                        "onTap": {
                          "innertubeCommand": {
                            "clickTrackingParams": "CAcQ8FsiEwjwic3PoL2OAxVM8EkHHQ_HOuw=",
                            "commandMetadata": {
                              "webCommandMetadata": {
                                "sendPost": true
                              }
                            },
                            "signalServiceEndpoint": {
                              "signal": "CLIENT_SIGNAL",
                              "actions": [
                                {
                                  "clickTrackingParams": "CAcQ8FsiEwjwic3PoL2OAxVM8EkHHQ_HOuw=",
                                  "addToPlaylistCommand": {
                                    "openMiniplayer": false,
                                    "openListPanel": true,
                                    "videoId": "vUuj6M8MgCg",
                                    "listType": "PLAYLIST_EDIT_LIST_TYPE_QUEUE",
                                    "onCreateListCommand": {
                                      "clickTrackingParams": "CAcQ8FsiEwjwic3PoL2OAxVM8EkHHQ_HOuw=",
                                      "commandMetadata": {
                                        "webCommandMetadata": {
                                          "sendPost": true,
                                          "apiUrl": "/youtubei/v1/playlist/create"
                                        }
                                      },
                                      "createPlaylistServiceEndpoint": {
                                        "videoIds": [
                                          "vUuj6M8MgCg"
                                        ],
                                        "params": "CAQ%3D"
                                      }
                                    },
                                    "videoIds": [
                                      "vUuj6M8MgCg"
                                    ],
                                    "videoCommand": {
                                      "clickTrackingParams": "CAcQ8FsiEwjwic3PoL2OAxVM8EkHHQ_HOuw=",
                                      "commandMetadata": {
                                        "webCommandMetadata": {
                                          "url": "/watch?v=vUuj6M8MgCg",
                                          "webPageType": "WEB_PAGE_TYPE_WATCH",
                                          "rootVe": 3832
                                        }
                                      },
                                      "watchEndpoint": {
                                        "videoId": "vUuj6M8MgCg",
                                        "watchEndpointSupportedOnesieConfig": {
                                          "html5PlaybackOnesieConfig": {
                                            "commonConfig": {
                                              "url": "https://rr3---sn-uxaxpu5ap5-c1ve.googlevideo.com/initplayback?source=youtube&oeis=1&c=WEB&oad=3200&ovd=3200&oaad=11000&oavd=11000&ocs=700&oewis=1&oputc=1&ofpcc=1&msp=1&odepv=1&onvi=1&id=bd4ba3e8cf0c8028&ip=82.52.46.4&initcwndbps=1918750&mt=1752526890&oweuc="
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              ]
                            }
                          }
                        },
                        "accessibilityText": "Add to queue",
                        "style": "BUTTON_VIEW_MODEL_STYLE_OVERLAY_DARK",
                        "trackingParams": "CAcQ8FsiEwjwic3PoL2OAxVM8EkHHQ_HOuw=",
                        "type": "BUTTON_VIEW_MODEL_TYPE_TONAL",
                        "buttonSize": "BUTTON_VIEW_MODEL_SIZE_COMPACT",
                        "state": "BUTTON_VIEW_MODEL_STATE_ACTIVE"
                      }
                    },
                    "toggledButtonViewModel": {
                      "buttonViewModel": {
                        "iconName": "CHECK",
                        "accessibilityText": "Added",
                        "style": "BUTTON_VIEW_MODEL_STYLE_OVERLAY_DARK",
                        "trackingParams": "CAYQ8FsiEwjwic3PoL2OAxVM8EkHHQ_HOuw=",
                        "type": "BUTTON_VIEW_MODEL_TYPE_TONAL",
                        "buttonSize": "BUTTON_VIEW_MODEL_SIZE_COMPACT",
                        "state": "BUTTON_VIEW_MODEL_STATE_ACTIVE"
                      }
                    },
                    "isToggled": false,
                    "trackingParams": "CAIQ1MQMGBUiEwjwic3PoL2OAxVM8EkHHQ_HOuw="
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "metadata": {
      "lockupMetadataViewModel": {
        "title": {
          "content": "Classical\\Piano Music to relax\\study to | Radio Version of my Live Streams"
        },
        "image": {
          "decoratedAvatarViewModel": {
            "avatar": {
              "avatarViewModel": {
                "image": {
                  "sources": [
                    {
                      "url": "https://yt3.ggpht.com/SmZ4IEb2-pwoqvLeVFqsLxxCFEsYvyE9BELNgZwzzCXzI2KZERN2olf_-PhTuNheJ_zXYEVdLw=s68-c-k-c0x00ffffff-no-rj",
                      "width": 68,
                      "height": 68
                    }
                  ]
                },
                "avatarImageSize": "AVATAR_SIZE_M"
              }
            },
            "a11yLabel": "Go to channel",
            "rendererContext": {
              "commandContext": {
                "onTap": {
                  "innertubeCommand": {
                    "clickTrackingParams": "CAIQ1MQMGBUiEwjwic3PoL2OAxVM8EkHHQ_HOuw=",
                    "commandMetadata": {
                      "webCommandMetadata": {
                        "url": "/@enricovincente",
                        "webPageType": "WEB_PAGE_TYPE_CHANNEL",
                        "rootVe": 3611,
                        "apiUrl": "/youtubei/v1/browse"
                      }
                    },
                    "browseEndpoint": {
                      "browseId": "UCWa_Jqdcs3nBPpPPEiIMq4A",
                      "canonicalBaseUrl": "/@enricovincente"
                    }
                  }
                }
              }
            }
          }
        },
        "metadata": {
          "contentMetadataViewModel": {
            "metadataRows": [
              {
                "metadataParts": [
                  {
                    "text": {
                      "content": "Enrico Vincente",
                      "styleRuns": [
                        {
                          "startIndex": 15,
                          "styleRunExtensions": {
                            "styleRunColorMapExtension": {
                              "colorMap": [
                                {
                                  "key": "USER_INTERFACE_THEME_LIGHT",
                                  "value": 4284506208
                                },
                                {
                                  "key": "USER_INTERFACE_THEME_DARK",
                                  "value": 4289374890
                                }
                              ]
                            }
                          }
                        }
                      ],
                      "attachmentRuns": [
                        {
                          "startIndex": 15,
                          "length": 0,
                          "element": {
                            "type": {
                              "imageType": {
                                "image": {
                                  "sources": [
                                    {
                                      "clientResource": {
                                        "imageName": "CHECK_CIRCLE_FILLED"
                                      },
                                      "width": 14,
                                      "height": 14
                                    }
                                  ]
                                }
                              }
                            },
                            "properties": {
                              "layoutProperties": {
                                "height": {
                                  "value": 14,
                                  "unit": "DIMENSION_UNIT_POINT"
                                },
                                "width": {
                                  "value": 14,
                                  "unit": "DIMENSION_UNIT_POINT"
                                },
                                "margin": {
                                  "left": {
                                    "value": 4,
                                    "unit": "DIMENSION_UNIT_POINT"
                                  }
                                }
                              }
                            }
                          },
                          "alignment": "ALIGNMENT_VERTICAL_CENTER"
                        }
                      ]
                    }
                  }
                ]
              }
            ],
            "delimiter": " • "
          }
        },
        "menuButton": {
          "buttonViewModel": {
            "iconName": "MORE_VERT",
            "onTap": {
              "innertubeCommand": {
                "clickTrackingParams": "CAMQ8FsiEwjwic3PoL2OAxVM8EkHHQ_HOuw=",
                "showSheetCommand": {
                  "panelLoadingStrategy": {
                    "inlineContent": {
                      "sheetViewModel": {
                        "content": {
                          "listViewModel": {
                            "listItems": [
                              {
                                "listItemViewModel": {
                                  "title": {
                                    "content": "Add to queue"
                                  },
                                  "leadingImage": {
                                    "sources": [
                                      {
                                        "clientResource": {
                                          "imageName": "ADD_TO_QUEUE_TAIL"
                                        }
                                      }
                                    ]
                                  },
                                  "rendererContext": {
                                    "loggingContext": {
                                      "loggingDirectives": {
                                        "trackingParams": "CAUQ_pgEGAAiEwjwic3PoL2OAxVM8EkHHQ_HOuw="
                                      }
                                    },
                                    "commandContext": {
                                      "onTap": {
                                        "innertubeCommand": {
                                          "clickTrackingParams": "CAUQ_pgEGAAiEwjwic3PoL2OAxVM8EkHHQ_HOuw=",
                                          "commandMetadata": {
                                            "webCommandMetadata": {
                                              "sendPost": true
                                            }
                                          },
                                          "signalServiceEndpoint": {
                                            "signal": "CLIENT_SIGNAL",
                                            "actions": [
                                              {
                                                "clickTrackingParams": "CAUQ_pgEGAAiEwjwic3PoL2OAxVM8EkHHQ_HOuw=",
                                                "addToPlaylistCommand": {
                                                  "openMiniplayer": true,
                                                  "videoId": "vUuj6M8MgCg",
                                                  "listType": "PLAYLIST_EDIT_LIST_TYPE_QUEUE",
                                                  "onCreateListCommand": {
                                                    "clickTrackingParams": "CAUQ_pgEGAAiEwjwic3PoL2OAxVM8EkHHQ_HOuw=",
                                                    "commandMetadata": {
                                                      "webCommandMetadata": {
                                                        "sendPost": true,
                                                        "apiUrl": "/youtubei/v1/playlist/create"
                                                      }
                                                    },
                                                    "createPlaylistServiceEndpoint": {
                                                      "videoIds": [
                                                        "vUuj6M8MgCg"
                                                      ],
                                                      "params": "CAQ%3D"
                                                    }
                                                  },
                                                  "videoIds": [
                                                    "vUuj6M8MgCg"
                                                  ],
                                                  "videoCommand": {
                                                    "clickTrackingParams": "CAUQ_pgEGAAiEwjwic3PoL2OAxVM8EkHHQ_HOuw=",
                                                    "commandMetadata": {
                                                      "webCommandMetadata": {
                                                        "url": "/watch?v=vUuj6M8MgCg",
                                                        "webPageType": "WEB_PAGE_TYPE_WATCH",
                                                        "rootVe": 3832
                                                      }
                                                    },
                                                    "watchEndpoint": {
                                                      "videoId": "vUuj6M8MgCg",
                                                      "watchEndpointSupportedOnesieConfig": {
                                                        "html5PlaybackOnesieConfig": {
                                                          "commonConfig": {
                                                            "url": "https://rr3---sn-uxaxpu5ap5-c1ve.googlevideo.com/initplayback?source=youtube&oeis=1&c=WEB&oad=3200&ovd=3200&oaad=11000&oavd=11000&ocs=700&oewis=1&oputc=1&ofpcc=1&msp=1&odepv=1&onvi=1&id=bd4ba3e8cf0c8028&ip=82.52.46.4&initcwndbps=1918750&mt=1752526890&oweuc="
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            ]
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              },
                              {
                                "downloadListItemViewModel": {
                                  "rendererContext": {
                                    "commandContext": {
                                      "onTap": {
                                        "innertubeCommand": {
                                          "clickTrackingParams": "CAMQ8FsiEwjwic3PoL2OAxVM8EkHHQ_HOuw=",
                                          "offlineVideoEndpoint": {
                                            "videoId": "vUuj6M8MgCg",
                                            "onAddCommand": {
                                              "clickTrackingParams": "CAMQ8FsiEwjwic3PoL2OAxVM8EkHHQ_HOuw=",
                                              "getDownloadActionCommand": {
                                                "videoId": "vUuj6M8MgCg",
                                                "params": "CAIQAA%3D%3D"
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              },
                              {
                                "listItemViewModel": {
                                  "title": {
                                    "content": "Share"
                                  },
                                  "leadingImage": {
                                    "sources": [
                                      {
                                        "clientResource": {
                                          "imageName": "SHARE"
                                        }
                                      }
                                    ]
                                  },
                                  "rendererContext": {
                                    "commandContext": {
                                      "onTap": {
                                        "innertubeCommand": {
                                          "clickTrackingParams": "CAMQ8FsiEwjwic3PoL2OAxVM8EkHHQ_HOuw=",
                                          "commandMetadata": {
                                            "webCommandMetadata": {
                                              "sendPost": true,
                                              "apiUrl": "/youtubei/v1/share/get_share_panel"
                                            }
                                          },
                                          "shareEntityServiceEndpoint": {
                                            "serializedShareEntity": "Cgt2VXVqNk04TWdDZw%3D%3D",
                                            "commands": [
                                              {
                                                "clickTrackingParams": "CAMQ8FsiEwjwic3PoL2OAxVM8EkHHQ_HOuw=",
                                                "openPopupAction": {
                                                  "popup": {
                                                    "unifiedSharePanelRenderer": {
                                                      "trackingParams": "CAQQjmIiEwjwic3PoL2OAxVM8EkHHQ_HOuw=",
                                                      "showLoadingSpinner": true
                                                    }
                                                  },
                                                  "popupType": "DIALOG",
                                                  "beReused": true
                                                }
                                              }
                                            ]
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            ]
                          }
                        }
                      }
                    }
                  }
                }
              }
            },
            "accessibilityText": "More actions",
            "style": "BUTTON_VIEW_MODEL_STYLE_MONO",
            "trackingParams": "CAMQ8FsiEwjwic3PoL2OAxVM8EkHHQ_HOuw=",
            "type": "BUTTON_VIEW_MODEL_TYPE_TEXT",
            "buttonSize": "BUTTON_VIEW_MODEL_SIZE_DEFAULT",
            "state": "BUTTON_VIEW_MODEL_STATE_ACTIVE"
          }
        }
      }
    },
    "contentId": "vUuj6M8MgCg",
    "contentType": "LOCKUP_CONTENT_TYPE_VIDEO",
    "rendererContext": {
      "loggingContext": {
        "loggingDirectives": {
          "trackingParams": "CAIQ1MQMGBUiEwjwic3PoL2OAxVM8EkHHQ_HOuw=",
          "visibility": {
            "types": "12"
          }
        }
      },
      "accessibilityContext": {
        "label": "Classical\\Piano Music to relax\\study to | Radio Version of my Live Streams"
      },
      "commandContext": {
        "onTap": {
          "innertubeCommand": {
            "clickTrackingParams": "CAIQ1MQMGBUiEwjwic3PoL2OAxVM8EkHHQ_HOuxIvY2jn_bg2bwqmgEFCAEQ-B0=",
            "commandMetadata": {
              "webCommandMetadata": {
                "url": "/watch?v=vUuj6M8MgCg",
                "webPageType": "WEB_PAGE_TYPE_WATCH",
                "rootVe": 3832
              }
            },
            "watchEndpoint": {
              "videoId": "vUuj6M8MgCg",
              "nofollow": true,
              "watchEndpointSupportedOnesieConfig": {
                "html5PlaybackOnesieConfig": {
                  "commonConfig": {
                    "url": "https://rr3---sn-uxaxpu5ap5-c1ve.googlevideo.com/initplayback?source=youtube&oeis=1&c=WEB&oad=3200&ovd=3200&oaad=11000&oavd=11000&ocs=700&oewis=1&oputc=1&ofpcc=1&msp=1&odepv=1&onvi=1&id=bd4ba3e8cf0c8028&ip=82.52.46.4&initcwndbps=1918750&mt=1752526890&oweuc="
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

</details>

**Review by Stypox — CHANGES_REQUESTED** [review]
Thank you! I left a few comments but it's nothing important, everything else LGTM

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java (hunk 11 above)
Comment (litetex) [reply extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java]: I think there is no harm in keeping the existing code.

It should be even better performance wise because we don't have to call the same method again.

Comment (Stypox) [reply extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java]: Yeah

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java (hunk 14 above)
Comment (litetex) [reply extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java]: I think there is a problem in the related javadoc of this method:

> the number of views or -1 for live streams

This is not how the it's used in NewPipe:

https://github.com/TeamNewPipe/NewPipe/blob/3f37e27852a2d7559722bc69e7233ded68730ab1/app/src/main/java/org/schabi/newpipe/info_list/holder/StreamInfoItemHolder.java#L67-L78

I will fix the javadoc and the method :)

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java (hunk 12 above)
Comment (litetex) [reply extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java:174]: I also had this thought however who knows what YT is changing in the future so the complete object might look different in 10 days (this was a "Trending will be shut down next week"-pun :D) 

Can you maybe pack this into a issue called "Improve YoutubeStreamInfoItemLockupExtractor's metadata-part extraction`` or something similar? So that it's not forgotten :)

Comment (Stypox) [reply extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java:174]: Done: https://github.com/TeamNewPipe/NewPipeExtractor/issues/1336

File: extractor/src/main/java/org/schabi/newpipe/extractor/stream/StreamInfoItemExtractor.java [hunk 15]
```diff
@@ -58,7 +58,7 @@ public interface StreamInfoItemExtractor extends InfoItemExtractor {
     /**
      * Parses the number of views
      *
-     * @return the number of views or -1 for live streams
+     * @return the number of views or -1 if not available
```
Comment (Stypox) [inline extractor/src/main/java/org/schabi/newpipe/extractor/stream/StreamInfoItemExtractor.java]: Maybe
```
     * Parses the number of views (or of current viewers in case of live streams)
     *
     * @return the number of views (or of current viewers in case of live streams) or -1 if not available
```

**Review by Stypox — APPROVED** [review]
Thanks, LGTM!

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java [hunk 16]
```diff
@@ -0,0 +1,398 @@
...
+        if (!isNullOrEmpty(name)) {
+            this.cachedName = name;
+            return name;
+        }
+        throw new ParsingException("Could not get name");
+    }
+
+    @Override
+    public long getDuration() throws ParsingException {
+        // Duration can not be extract from live streams, only from normal videos
```
Comment (AudricV) [inline extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemLockupExtractor.java]:
```suggestion
        // Duration can not be extracted from live streams, only from normal videos
```
