### PR TITLE
[YouTube] Fix ParsingException when comments are unavailable in a video

### LINKED ISSUE #969: [YouTube] ParsingException thrown when comments are unavailable in a video
Example video: https://piped.kavin.rocks/watch?v=92d75BMvevs
Test with PipedAPI: https://pipedapi.kavin.rocks/comments/92d75BMvevs

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Unable to get contents.twoColumnWatchNextResults.results.results.contents
    at org.schabi.newpipe.extractor.utils.JsonUtils.getValue(JsonUtils.java:36)
    at org.schabi.newpipe.extractor.utils.JsonUtils.getInstanceOf(JsonUtils.java:44)
    at org.schabi.newpipe.extractor.utils.JsonUtils.getArray(JsonUtils.java:80)
    at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.findInitialCommentsToken(YoutubeCommentsExtractor.java:83)
    at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.isCommentsDisabled(YoutubeCommentsExtractor.java:272)
    at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:49)
    at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:29)
    at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:24)
```

### PR DESCRIPTION
**Pull request by bjoernls**
Issue #969. Parsing exception is handled when the JSON path does not exist in the case of disabled comments.

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [ ] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

Fixes #969

The output is now
`{"comments":[],"nextpage":null,"disabled":true}`

### CODE REVIEW

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeCommentsExtractor.java [hunk 1]
```diff
@@ -105,6 +104,16 @@ private String findInitialCommentsToken(final JsonObject nextResponse)
         return token;
     }
 
+    @Nonnull
+    private JsonArray getJsonContents(final JsonObject nextResponse) {
+        try {
+            return JsonUtils.getArray(nextResponse,
+                    "contents.twoColumnWatchNextResults.results.results.contents");
+        } catch (final ParsingException pe) {
```
Comment (AudricV) [inline extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeCommentsExtractor.java:112]: You don't need to use `pe`, you could just `e` for the exception in this context:

```suggestion
        } catch (final ParsingException e) {
```

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeCommentsExtractor.java [hunk 2]
```diff
@@ -105,6 +104,16 @@ private String findInitialCommentsToken(final JsonObject nextResponse)
...
+            return new JsonArray(Collections.emptyList());
```
Comment (AudricV) [inline extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeCommentsExtractor.java:113]: Why do you want to use the constructor with a `Collection` where you pass an empty list? Can't you just use an empty `JsonArray` instead?

**Review by AudricV — CHANGES_REQUESTED** [review]
Thanks for this fix!

Please use appropriate PR and commit names in the future: do not repeat the issue title but describe what you did for both things (so in this case it would be something like "[YouTube] Fix ParsingException when getting comments on videos without comments").

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeCommentsExtractor.java (hunk 2 above)
Comment (bjoernls) [reply extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeCommentsExtractor.java:113]: It's a coding convention I've become accustomed to. The line of thinking is that the function returns the content of the JSON, and should be read-only.

Comment (bjoernls) [reply extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeCommentsExtractor.java:113]: Ok :)

**Review by AudricV — APPROVED** [review]
