### PR TITLE
Faster iframe api based player extraction.

### LINKED ISSUE #693: Make YoutubeJavaScriptExtractor more robust
`YoutubeJavaScriptExtractor` currently sometimes failes to find the javascript file , which contains the multiple decryption functions.  
See TODO in file https://github.com/TeamNewPipe/NewPipeExtractor/blob/14c179f343ab8ed703f81cc2956f4802958c6c30/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeJavaScriptExtractor.java#L74

see crash TeamNewPipe/NewPipe#6780

### PR DESCRIPTION
**Pull request by FireMasterK**
Uses the IFrame API to reduce the required download to less than 1/50 of the size.

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [ ] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

Closes #693?

### CODE REVIEW

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeJavaScriptExtractor.java [hunk 1]
```diff
@@ -62,29 +62,42 @@ public static String extractJavaScriptCode() throws ParsingException {
...
+            final String iframeUrl = "https://www.youtube.com/iframe_api";
+            final String iframeContent = NewPipe.getDownloader()
+                    .get(iframeUrl, Localization.DEFAULT).responseBody();
+            final String hashPattern = "player\\\\\\/([a-z0-9]{8})\\\\\\/";
+            final String hash = Parser.matchGroup1(hashPattern, iframeContent);
 
+            return String.format("https://www.youtube.com/s/player/%s/player_ias.vflset/en_US/base.js", hash);
+
+        } catch (Exception i) {
+            i.printStackTrace();
```
Comment (XiangRongLin) [inline extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeJavaScriptExtractor.java:74]: remove

**Review by XiangRongLin — COMMENTED** [review]
Do you have some examples to back  up the 1/50 size claim?

**Comment by FireMasterK** [comment]
> Do you have some examples to back up the 1/50 size claim?

Yes, I do, in fact, it's a bit more than that:
image
image

**Review by XiangRongLin — COMMENTED** [review]
Can you think of a way to somehow automatically test if your new implementation is actually used and it does not just always go to the `catch` block with the old implementation?

I can't think of anything right away, besides making everything public.

Edit: Reasoning being that the current tests either only cover your new implementation or the old one and not both

**Comment by FireMasterK** [comment]
What would you like to happen if the new implementation fails?

Printing an error?

I could move then over to two methods so that they can be individually tested.

**Comment by XiangRongLin** [comment]
> What would you like to happen if the new implementation fails?
>
> Printing an error?

Normally i would say log it, but because there is no logging setup => do nothing

> I could move them over to two methods so that they can be individually tested.

Yeah that's probably the easiest thing

**Comment by FireMasterK** [comment]
Done! Another thing I noticed is that the current tests do not account for the fact that the `playerCode` can be cached, thereby making some tests poinless.

**Comment by XiangRongLin** [comment]
Can you also add tests for the 2 methods

> Another thing I noticed is that the current tests do not account for the fact that the playerCode can be cached, thereby making some tests pointless.

You can create an issue for it. I have a rough idea on how to solve it, but finding the time to do it may prove hard

**Comment by FireMasterK** [comment]
Done!

File: extractor/src/test/java/org/schabi/newpipe/extractor/services/youtube/YoutubeJavaScriptExtractorTest.java [hunk 2]
```diff
@@ -19,6 +19,16 @@ public void setup() throws IOException {
...
 
+    @Test
+    public void testExtractJavaScriptUrlIframe() throws ParsingException {
+        YoutubeJavaScriptExtractor.extractJavaScriptUrl();
+    }
+
+    @Test
+    public void testExtractJavaScriptUrlEmbed() throws ParsingException {
+        YoutubeJavaScriptExtractor.extractJavaScriptUrl("d4IGg5dqeO8");
+    }
```
Comment (XiangRongLin) [inline extractor/src/test/java/org/schabi/newpipe/extractor/services/youtube/YoutubeJavaScriptExtractorTest.java:30]: Can you add some assertions? As it stands, I could delete the whole implementation of the methods and these test would still pass.

Otherwise remove the tests/ undo you last commit.

Comment (FireMasterK) [reply extractor/src/test/java/org/schabi/newpipe/extractor/services/youtube/YoutubeJavaScriptExtractorTest.java:30]: Oh, I thought it was fine since it would throw an exception in case it can't find an URL. Is it still necessary to add some assertions?

Comment (XiangRongLin) [reply extractor/src/test/java/org/schabi/newpipe/extractor/services/youtube/YoutubeJavaScriptExtractorTest.java:30]: But what about the cases where it finds an url, but they don't lead to the player js file?

Comment (FireMasterK) [reply extractor/src/test/java/org/schabi/newpipe/extractor/services/youtube/YoutubeJavaScriptExtractorTest.java]: Resolved! I've made it check whether it ends with `base.js`, there are a lot of URL formats for the player URL, and hence I avoided using a regex.

**Review by XiangRongLin — APPROVED** [review]
Good enough, since i can't think of anything else either. As in better tests/rewriting for better testability
