### PR TITLE
Fix invalid yt url: signature tag name is not always "signature"

### LINKED ISSUE #162: cannot decrypt some video
hello,
some video such as https://www.youtube.com/watch?v=DTjdcgSXMwQ
when I repeat call, sometime cannot decrypt signature( use latest code), 
**** decryption code****
`var uv={lL:function(a){a.reverse()},NB:function(a,b){var c=a[0];a[0]=a[b%a.length];a[b%a.length]=c},nu:function(a,b){a.splice(0,b)}};var vv=function(a){a=a.split("");uv.NB(a,70);uv.NB(a,67);uv.NB(a,2);uv.NB(a,19);uv.lL(a,6);uv.NB(a,45);uv.NB(a,56);uv.nu(a,3);uv.lL(a,49);return a.join("")};function decrypt(a){return vv(a);}`

this info, can decrypt
`{itag=18, s=3B603054D4A80E0356E04F7D4E5EF5C396A271FE.6C50B059F5A51CCEA1A168CB473287E54BC1C82E821, quality=medium, type=video/mp4; codecs="avc1.42001E, mp4a.40.2", sp=signature, url=XXXX`

this info, cannot decrypt
`{itag=18, s=TL5xI2wwRQIhANJE_8nAuKPeSKt26hPGlE5TFmBCId8-7dU4hO=o8gkDAiBQXHjXWMXgELnNT17VH_fCgKF3pYpuPIbpU10SBUybvQ==Q=3, quality=medium, type=video/mp4; codecs="avc1.42001E, mp4a.40.2", sp=sig, url=XXXX`

****now i fixed it with
https://github.com/TeamNewPipe/NewPipeExtractor/issues/155#issuecomment-483033261

### PR DESCRIPTION
**Pull request by Stypox**
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I did test the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [no breaking change] I agree to ASAP create a PULL request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) for making in compatible when I changed the api.

Thanks to @omarroth for the suggestion. For more info see #155 #162 TeamNewPipe/NewPipe#2337

This should fix many problems users keep having in the last few weeks: some videos in NewPipe don't load, at random. Invalid urls of those videos are then cached, and the app won't load them anymore until the cache is wiped. So even after this pr is merged, users would still have to manually wipe metadata from the app.

I tested the changes in the NewPipe app and it worked normally with all the videos I tried. I also added a `Log` instruction to have the url printed in the android logcat, and I saw that both types* of YouTube links work (one of them wouldn't have worked previously).
###### * One type (the one that has always worked) has "id" as the first url tag and signature tag "signature", the other (that created problems with the signature) has "expire" as the first url tag and signature tag "sig". Or at least it seems to be like this, to me.

Please merge this as soon as possible, since this issue is affecting many people and is very annoying :-) .

Fixes #162
Fixes (partially) #155 
Fixes TeamNewPipe/NewPipe#2336
Fixes TeamNewPipe/NewPipe#2337
Fixes TeamNewPipe/NewPipe#2324
Fixes TeamNewPipe/NewPipe#2304
Fixes TeamNewPipe/NewPipe#2275
Probably also fixes TeamNewPipe/NewPipe#867
Probably also fixes TeamNewPipe/NewPipe#2297

### CODE REVIEW

**Comment by Stypox** [comment]
The unsuccessful checks are due to a video used to test comments that is not available anymore.

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamExtractor.java [hunk 1]
```diff
@@ -888,7 +888,7 @@ private static String getVideoInfoUrl(final String id, final String sts) {
                         String streamUrl = tags.get("url");
                         // if video has a signature: decrypt it and add it to the url
                         if (tags.get("s") != null) {
-                            streamUrl = streamUrl + "&signature=" + decryptSignature(tags.get("s"), decryptionCode);
+                            streamUrl = streamUrl + "&" + tags.get("sp") + "=" + decryptSignature(tags.get("s"), decryptionCode);
```
Comment (TobiGr) [inline extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamExtractor.java]: Thanks! I'd like to include this into 0.16.2 so we can get this fix out asap. Can we ensure that `tags.get("sp") != null`? If this is the case, we are good to go. Otherwise, I'd suggest to use `streamUrl = streamUrl + "&signature=" + decryptSignature(tags.get("s"), decryptionCode);` as fallback if `tags.get("sp") == null`.

**Comment by hp8wvvvgnj6asjm7** [comment]
asap pls!

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamExtractor.java (hunk 1 above)
Comment (Stypox) [reply extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamExtractor.java]: Ok, I'll implement and test it this evening

**Comment by Stypox** [comment]
Implemented and tested the suggestion from @TobiGr 
Even if we can ensure that `tags.get("sp") != null`, there is no way to guarantee that YouTube will never remove the signature name.
