### PR TITLE
[YouTube] Support handles and all channel usernames

### LINKED ISSUE #875: YouTube channel being detected as a PeerTube one
Put this in the search bar:
https://piped.kavin.rocks/c/%EB%85%B8%EB%A7%88%EB%93%9C%EC%BD%94%EB%8D%94NomadCoders

## Exception
* __User Action:__ requested channel
* __Request:__ Start loading: https://www.youtube.com/c/%EB%85%B8%EB%A7%88%EB%93%9C%EC%BD%94%EB%8D%94NomadCoders
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ PeerTube
* __Version:__ 0.23.1
* __OS:__ Linux Android 12 - 32
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ExtractionException: Unable to extract PeerTube channel data
	at org.schabi.newpipe.extractor.services.peertube.extractors.PeertubeChannelExtractor.setInitialData(PeertubeChannelExtractor.java:156)
	at org.schabi.newpipe.extractor.services.peertube.extractors.PeertubeChannelExtractor.onFetchPage(PeertubeChannelExtractor.java:146)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)
	at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:54)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getChannelInfo$4(ExtractorHelper.java:126)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$BOLWstv98dC8pFAG_uir5gPXYwY(Unknown Source:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda3.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15868)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: com.grack.nanojson.JsonParserException: Unexpected character: < on line 1, char 1
	at com.grack.nanojson.JsonTokener.createParseException(Unknown Source:44)
	at com.grack.nanojson.JsonTokener.advanceToToken(Unknown Source:118)
	at com.grack.nanojson.JsonParser.advanceToken(Unknown Source:12)
	at com.grack.nanojson.JsonParser.parse(Unknown Source:1)
	at com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source:19)
	at org.schabi.newpipe.extractor.services.peertube.extractors.PeertubeChannelExtractor.setInitialData(PeertubeChannelExtractor.java:154)
	... 30 more

```
</details>
<hr>

### PR DESCRIPTION
**Pull request by AudricV**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [x] I agree to create a pull request for [NewPipe](https://github.com/TeamNewPipe/NewPipe) as soon as possible to make it compatible with the changed API.

This PR adds support of [YouTube handles](https://blog.youtube/news-and-events/introducing-handles-a-new-way-to-identify-your-youtube-channel/) into the extractor, and supports all user IDs instead of only the ones which match [this regular expression](https://github.com/TeamNewPipe/NewPipeExtractor/blob/ffffb0443943d6f730535230d1542c79cae31344/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/linkHandler/YoutubeChannelLinkHandlerFactory.java#L101).

Furthermore, in this PR, I added more non-channels endpoints to the list of excluded endpoints, improved and fixed documentation, comments and exception messages of `YoutubeChannelLinkHandlerFactory`, and moved its license header, updated on the fly, at its beginning.

Finally, I added new tests for handles and for a channel which have characters which doesn't match the regular expression linked above, and removed the unneeded `public` test modifiers for `YoutubeChannelLinkHandlerFactoryTest`.

I also make use of a handle for resolving the Gronkh channel ID instead of its custom name, and updated the mocks of this test, as it was needed.

Fixes #875 and TeamNewPipe/NewPipe#9243 for the extractor implementation.

### CODE REVIEW

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/linkHandler/YoutubeChannelLinkHandlerFactory.java [hunk 1]
```diff
@@ -77,35 +92,38 @@ public String getId(final String url) throws ParsingException {
...
-                throw new ParsingException("the URL given is neither a channel nor an user");
+                throw new ParsingException(
+                        "The given URL is not a channel, a user or a handle URL");
             }
 
             final String id = splitPath[1];
 
-            if (id == null || !id.matches("[A-Za-z0-9_-]+")) {
-                throw new ParsingException("The given id is not a Youtube-Video-ID");
+            if (isBlank(id)) {
```
Comment (AudricV) [inline extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/linkHandler/YoutubeChannelLinkHandlerFactory.java:120]: Do you think we should use something else to match all custom names of channels or not?

Comment (TobiGr) [reply extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/linkHandler/YoutubeChannelLinkHandlerFactory.java:120]: Is it possible to have a channel ID that does not match the old pattern, e.g. by consisting of non latin characters?

Comment (TobiGr) [reply extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/linkHandler/YoutubeChannelLinkHandlerFactory.java:120]: Ok. dumb question. you put one into your tests... https://www.youtube.com/c/%EB%85%B8%EB%A7%88%EB%93%9C%EC%BD%94%EB%8D%94NomadCoders

**Review by TobiGr — APPROVED** [review]
