### PR TITLE
[YouTube] update iOS client, add visitor data to requests

### LINKED ISSUE #1259: Youtube "IOS player response is not valid" when opening a stream
### Checklist

- [x] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipeExtractor/releases/latest).
- [x] I am aware that this issue is being opened for the NewPipe Extractor, NOT the [app](https://github.com/TeamNewPipe/NewPipe), and my bug report will be dismissed otherwise.
- [x] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipeExtractor/issues) or [closed](https://github.com/TeamNewPipe/NewPipeExtractor/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [x] This issue contains only one bug.
- [x] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

v0.24.3

### Steps to reproduce the bug

The exception is not consistent.

1. Init NewPipe
2. Get info stream: `var info = StreamInfo.getInfo(NewPipe.getService(0), "https://youtube.com/watch?v=$id")`

### Expected behavior

Extractor to work without exceptions

### Actual behavior

Exception randomly happening: `org.schabi.newpipe.extractor.exceptions.ExtractionException: IOS player response is not valid`

### Screenshots/Screen recordings

n/a

### Logs

```
FATAL EXCEPTION: DefaultDispatcher-worker-1
Process: cc.wordview.app, PID: 26956
org.schabi.newpipe.extractor.exceptions.ExtractionException: IOS player response is not valid
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.fetchIosMobileJsonPlayer(YoutubeStreamExtractor.java:974)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:830)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:77)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
	at cc.wordview.app.extractor.VideoStream.init(VideoStream.kt:40)
	at cc.wordview.app.ui.screens.player.PlayerKt$Player$1$1.invokeSuspend(Player.kt:128)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c7de62a, Dispatchers.IO]

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Theta-Dev**
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- [X] No API changes

I have fixed the issue with the iOS client returning invalid responses
Apparently the only issue with the iOS client is that we were not sending it visitor data cookies. Since the visitor data cookies are just protobuf objects with a random ID, timestamp and country code, they can be randomly generated and dont need to be fetched from YouTube.

Fixes #1259
Fixes TeamNewPipe/NewPipe/issues/11934

### CODE REVIEW

**Comment by Stypox** [comment]
I just tested in NewPipe and it works, thank you!

**Comment by Theta-Dev** [comment]
Yes, it only works with the visitor data cookie. I first tried updating the client version and the issue was still there.

You can extract the visitor data cookie from YouTube, but that requires an extra request. I have been using random visitor data cookies in my own YouTube client for a few months now and they work without issues.

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/ProtoBuilder.java [hunk 1]
```diff
@@ -0,0 +1,71 @@
+package org.schabi.newpipe.extractor.services.youtube;
+
+import java.io.ByteArrayOutputStream;
+import java.io.IOException;
+import java.net.URLEncoder;
+import java.nio.charset.StandardCharsets;
+import java.util.Base64;
+
+public class ProtoBuilder {
```
[the remark this answers is not in the document]
Comment (Theta-Dev) [reply extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/ProtoBuilder.java:9]: Yes, it is generic, but afaik YouTube is the only platform that uses protobuf objects in various places (visitor data, continuation tokens, search parameters).

**Comment by Theta-Dev** [comment]
YouTube does store the visitor data as a cookie (__Secure-YEC), but probably also in local storage so it can be sent as an API parameter by the player code. It fulfills the role of an unique session ID so I call it a cookie. I dont know if there are better terms for it.

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeParsingHelper.java [hunk 2]
```diff
@@ -235,15 +235,15 @@ private YoutubeParsingHelper() {
      *
      * @see #IOS_USER_AGENT_VERSION
      */
-    private static final String IOS_OS_VERSION = "17.5.1.21F90";
+    private static final String IOS_OS_VERSION = "18.1.0.22B83";
 
     /**
      * Spoofing an iPhone 15 running iOS 17.5.1 with the hardcoded version of the iOS app. To be
```
Comment (Thymelizabeth) [inline extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeParsingHelper.java:241]: Shouldn't this comment change as well?

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeParsingHelper.java [hunk 3]
```diff
@@ -303,6 +303,23 @@ public static boolean isY2ubeURL(@Nonnull final URL url) {
         return url.getHost().equalsIgnoreCase("y2u.be");
     }
 
+    public static String randomVisitorData(final ContentCountry country) {
+        final ProtoBuilder pbE2 = new ProtoBuilder();
+        pbE2.string(2, "");
+        pbE2.varint(4, numberGenerator.nextInt(1, 256));
```
Comment (jamesdrake101) [inline extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeParsingHelper.java:309]: @Theta-Dev  This causes the build to fail as it is not supported in the JRE targeted

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/ProtoBuilder.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (Theta-Dev) [reply extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/ProtoBuilder.java]: okay, I moved the ProtoBuilder to the utils package

File: extractor/src/main/java/org/schabi/newpipe/extractor/utils/ProtoBuilder.java [hunk 4]
```diff
@@ -0,0 +1,72 @@
...
+                    v >>= 7;
+
+                    if (v != 0) {
+                        b |= (byte) 0x80;
+                    }
+                    byteBuffer.write(new byte[]{b});
+                }
+            }
+        } catch (final IOException e) {
+            throw new RuntimeException(e);
```
Comment (litetex) [inline extractor/src/main/java/org/schabi/newpipe/extractor/utils/ProtoBuilder.java:42]: Side note: It may be better to use ``UncheckedIOException`` here since it's more specific
This might be also relevant for the rest of the file ;)

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeParsingHelper.java [hunk 5]
```diff
@@ -1256,6 +1275,7 @@ public static JsonBuilder<JsonObject> prepareIosMobileJsonBuilder(
                         .value("platform", "MOBILE")
                         .value("osName", "iOS")
                         .value("osVersion", IOS_OS_VERSION)
+                        .value("visitorData", randomVisitorData(contentCountry))
```
Comment (litetex) [inline extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeParsingHelper.java:1278]: Can this be the same as ``vData``?

Maybe add a short comment into the code that documents this

File: extractor/src/main/java/org/schabi/newpipe/extractor/utils/ProtoBuilder.java [hunk 6]
```diff
@@ -0,0 +1,72 @@
+package org.schabi.newpipe.extractor.utils;
+
+import java.io.ByteArrayOutputStream;
+import java.io.IOException;
+import java.net.URLEncoder;
+import java.nio.charset.StandardCharsets;
+import java.util.Base64;
+
+public class ProtoBuilder {
```
Comment (litetex) [inline extractor/src/main/java/org/schabi/newpipe/extractor/utils/ProtoBuilder.java:9]: Some documentation would be nice, e.g. what this class does

**Review by litetex — COMMENTED** [review]
Some minor things that I would change.
But anyway nice PR!

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeParsingHelper.java [hunk 7]
```diff
@@ -212,7 +213,7 @@ private YoutubeParsingHelper() {
             "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
 
     /**
-     * The device machine id for the iPhone 15, used to get 60fps with the {@code iOS} client.
+     * The device machine id for the iPhone 16, used to get 60fps with the {@code iOS} client.
```
Comment (Stypox) [inline extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeParsingHelper.java:216]:
```suggestion
     * The device machine id for the iPhone 15, used to get 60fps with the {@code iOS} client.
```

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeParsingHelper.java [hunk 8]
```diff
@@ -222,28 +223,28 @@ private YoutubeParsingHelper() {
     private static final String IOS_DEVICE_MODEL = "iPhone16,2";
 
     /**
-     * Spoofing an iPhone 15 Pro Max running iOS 17.5.1 with the hardcoded version of the iOS app.
+     * Spoofing an iPhone 16 Pro Max running iOS 18.1.0 with the hardcoded version of the iOS app.
```
Comment (Stypox) [inline extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeParsingHelper.java:226]:
```suggestion
     * Spoofing an iPhone 15 Pro Max running iOS 18.1.0 with the hardcoded version of the iOS app.
```

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeParsingHelper.java [hunk 9]
```diff
@@ -222,28 +223,28 @@ private YoutubeParsingHelper() {
...
      * To be used for the {@code "osVersion"} field in JSON POST requests.
      * <p>
      * The value of this field seems to use the following structure:
      * "iOS major version.minor version.patch version.build version", where
      * "patch version" is equal to 0 if it isn't set
      * The build version corresponding to the iOS version used can be found on
-     * <a href="https://theapplewiki.com/wiki/Firmware/iPhone/17.x#iPhone_15_Pro_Max">
-     *     https://theapplewiki.com/wiki/Firmware/iPhone/17.x#iPhone_15_Pro_Max</a>
+     * <a href="https://theapplewiki.com/wiki/Firmware/iPhone/18.x#iPhone_16_Pro_Max">
+     *     https://theapplewiki.com/wiki/Firmware/iPhone/18.x#iPhone_16_Pro_Max</a>
```
Comment (Stypox) [inline extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeParsingHelper.java:234]:
```suggestion
     * <a href="https://theapplewiki.com/wiki/Firmware/iPhone/18.x#iPhone_15_Pro_Max">
     *     https://theapplewiki.com/wiki/Firmware/iPhone/18.x#iPhone_15_Pro_Max</a>
```

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeParsingHelper.java [hunk 10]
```diff
@@ -1392,7 +1412,7 @@ public static String getAndroidUserAgent(@Nullable final Localization localizati
      */
     @Nonnull
     public static String getIosUserAgent(@Nullable final Localization localization) {
-        // Spoofing an iPhone 15 running iOS 17.5.1 with the hardcoded version of the iOS app
+        // Spoofing an iPhone 16 Pro Max running iOS 18.1.0 with the hardcoded version of the iOS app
```
Comment (Stypox) [inline extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeParsingHelper.java:1415]:
```suggestion
        // Spoofing an iPhone 15 Pro Max running iOS 18.1.0 with the hardcoded version of the iOS app
```

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeParsingHelper.java [hunk 11]
```diff
@@ -222,28 +223,28 @@ private YoutubeParsingHelper() {
...
      * </p>
      *
      * @see #IOS_USER_AGENT_VERSION
      */
-    private static final String IOS_OS_VERSION = "17.5.1.21F90";
+    private static final String IOS_OS_VERSION = "18.1.0.22B83";
 
     /**
-     * Spoofing an iPhone 15 running iOS 17.5.1 with the hardcoded version of the iOS app. To be
+     * Spoofing an iPhone 16 Pro Max running iOS 18.1.0 with the hardcoded version of the iOS app. To be
```
Comment (Stypox) [inline extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeParsingHelper.java:242]:
```suggestion
     * Spoofing an iPhone 15 Pro Max running iOS 18.1.0 with the hardcoded version of the iOS app. To be
```

**Review by Stypox — APPROVED** [review]
Thank you a lot! I am going to release a new version right now, as I don't have too much time in the next few days and don't want to keep users waiting. So I'm merging this PR despite there being some finishing touches to do still.

@Theta-Dev please open a new PR to address the review comments. And @litetex @gechoto please continue the review in the other PR that is going to be opened. And thanks for reviewing :-)

**Comment by jamesdrake101** [comment]
Thank you 💯 for fast-tracking this

**Comment by Stypox** [comment]
@Theta-Dev friendly reminder to open a follow-up PR to add more documentation

**Comment by Theta-Dev** [comment]
AFAIK YouTube random visitor data IDs stopped working this week, so I guess we can remove the visitor data generator again.
