### PR TITLE
[YouTube] Fix search subscriber count extraction with channel handles

### LINKED ISSUE #976: [YouTube] Stream count and subscriber count extraction broken in search results with the introduction of handles
See [this CI run](https://github.com/TeamNewPipe/NewPipeExtractor/actions/runs/3501355793/jobs/5864925045#step:5:223):

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get subscriber count
    at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelInfoItemExtractor.getSubscriberCount(YoutubeChannelInfoItemExtractor.java:84)
    at org.schabi.newpipe.extractor.channel.ChannelInfoItemsCollector.extract(ChannelInfoItemsCollector.java:40)
    at org.schabi.newpipe.extractor.MultiInfoItemsCollector.extract(MultiInfoItemsCollector.java:84)
    at org.schabi.newpipe.extractor.MultiInfoItemsCollector.extract(MultiInfoItemsCollector.java:48)
    at org.schabi.newpipe.extractor.InfoItemsCollector.commit(InfoItemsCollector.java:104)
    at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.collectStreamsFrom(YoutubeSearchExtractor.java:226)
    at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getInitialPage(YoutubeSearchExtractor.java:162)
    at org.schabi.newpipe.extractor.services.DefaultTests.defaultTestRelatedItems(DefaultTests.java:114)
    ... 85 more

    Caused by:
    org.schabi.newpipe.extractor.utils.Parser$RegexException: Failed to find pattern "([\d]+([\.,][\d]+)?)" inside of "@AmericasTestKitchen"
        at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:75)
        at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:60)
        at org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:49)
        at org.schabi.newpipe.extractor.utils.Utils.mixedNumberWordToLong(Utils.java:98)
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelInfoItemExtractor.getSubscriberCount(YoutubeChannelInfoItemExtractor.java:81)
        ... 92 more
```

The handle of the YouTube channel is parsed instead of the subscriber count, due to a YouTube change which uses the `videoCountText` object for the subscriber count and the `subscriberCountText` for the handle:

yt_handles_search_results

You can reproduce this behavior by using the following `visitorData`: `CgszYlc1Yk1WZGRCSSjrwOSbBg%3D%3D`.

The stream count of a channel is not provided anymore in this case.

### PR DESCRIPTION
**Pull request by Theta-Dev**
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I have tested the API against [NewPipe](https://github.com/TeamNewPipe/NewPipe).
- no API changes

I fixed the extraction of channels' subscriber count and the error when trying to extract channel public videos count in search results with the new channel handles.

Fixes #976, fixes TeamNewPipe/NewPipe#9442.

### CODE REVIEW

File: extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeChannelInfoItemExtractor.java [hunk 1]
```diff
@@ -88,7 +110,7 @@ public long getSubscriberCount() throws ParsingException {
     @Override
     public long getStreamCount() throws ParsingException {
         try {
-            if (!channelInfoItem.has("videoCountText")) {
+            if (withHandle || !channelInfoItem.has("videoCountText")) {
                 // Video count is not available, channel probably has no public uploads.
```
Comment (AudricV) [inline extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeChannelInfoItemExtractor.java:114]: Could you tweak this comment, as it is a bit outdated now?

**Review by AudricV — COMMENTED** [review]
Thanks, changes look good to me!

**Review by AudricV — APPROVED** [review]

**Review by FireMasterK — APPROVED** [review]
